export const ADD_CLIMBS = 'ADD_CLIMBS'
export const CLIMBS_LOADING = 'CLIMBS_LOADING'
export const CLIMBS_FAILED = 'CLIMBS_FAILED'

export const ADD_LOCATIONS = 'ADD_LOCATIONS'
export const LOCATIONS_LOADING = 'LOCATIONS_LOADING'
export const LOCATIONS_FAILED = 'LOCATIONS_FAILED'

export const SENDS_LOADING = 'SENDS_LOADING'
export const SENDS_FAILED = 'SENDS_FAILED'
export const ADD_SENDS = 'ADD_SENDS'

export const TODOS_LOADING = 'TODOS_LOADING'
export const TODOS_FAILED = 'TODOS_FAILED'
export const ADD_TODOS = 'ADD_TODOS'

// export const ADD_COMMENTS = 'ADD_COMMENTS';
// export const COMMENTS_FAILED = 'COMMENTS_FAILED';
// export const ADD_COMMENT = 'ADD_COMMENT';
